# Understand Code — GitHub Action
# Adds comprehension questions as PR comments on significant code changes.
#
# Usage: Copy to .github/workflows/understand.yml in your repo
#
# Required secrets:
#   OPENROUTER_API_KEY — OpenRouter API key for LLM access
#
# Optional env:
#   UNDERSTAND_MODEL — LLM model (default: claude-sonnet-4)
#   UNDERSTAND_MIN_LINES — Minimum changed lines to trigger (default: 20)

name: Understand Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  comprehension-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check changed lines
        id: changes
        run: |
          CHANGED=$(git diff --numstat origin/${{ github.base_ref }}...HEAD | \
            grep -vE '\.(md|json|txt|jpg|png|mp4|lock)$' | \
            grep -v 'node_modules/' | \
            awk '{sum += $1 + $2} END {print sum+0}')
          echo "lines=$CHANGED" >> $GITHUB_OUTPUT
          echo "Changed lines: $CHANGED"

      - name: Generate comprehension questions
        if: ${{ fromJson(steps.changes.outputs.lines) >= fromJson(vars.UNDERSTAND_MIN_LINES || '20') }}
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          UNDERSTAND_MODEL: ${{ vars.UNDERSTAND_MODEL || 'anthropic/claude-sonnet-4' }}
        run: |
          CHANGED=${{ steps.changes.outputs.lines }}
          
          # Generate comprehension questions from git diff
          npx understand-code --git-diff --count 3 --format markdown > /tmp/questions.md 2>/dev/null || true
          
          if [ -s /tmp/questions.md ]; then
            echo "## 🧠 Comprehension Check" > /tmp/comment.md
            echo "" >> /tmp/comment.md
            echo "These questions test understanding of the changes in this PR." >> /tmp/comment.md
            echo "Can you answer them without looking at the diff?" >> /tmp/comment.md
            echo "" >> /tmp/comment.md
            cat /tmp/questions.md >> /tmp/comment.md
            echo "" >> /tmp/comment.md
            echo "---" >> /tmp/comment.md
            echo "*Generated by [understand-code](https://npmjs.com/package/understand-code). ${CHANGED} lines changed.*" >> /tmp/comment.md
          fi

      - name: Post PR comment
        if: ${{ fromJson(steps.changes.outputs.lines) >= fromJson(vars.UNDERSTAND_MIN_LINES || '20') }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('/tmp/comment.md', 'utf8');
            if (comment.trim()) {
              // Find and update existing comment or create new
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              });
              const existing = comments.find(c => c.body.includes('Comprehension Check'));
              if (existing) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existing.id,
                  body: comment,
                });
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: comment,
                });
              }
            }
